#!/bin/bash
gclone https://gitlab.edgecenter.io/edgesense/epack.git
gclone https://gitlab.edgecenter.io/edgesense/advins-template.git
gclone https://gitlab.edgecenter.io/edgesense/support-i-alarm-node.js.git
gclone https://gitlab.edgecenter.io/edgesense/advsc.git
gclone https://gitlab.edgecenter.io/edgesense/APIGateway.git
gclone https://gitlab.edgecenter.io/edgesense/mqttbroker.git
gclone https://gitlab.edgecenter.io/edgesense/Service-SDK.git
gclone https://gitlab.edgecenter.io/edgesense/device-net-monitor.git
gclone https://gitlab.edgecenter.io/edgesense/device-process-monitor.git

gclone https://gitlab.edgecenter.io/edgesense/device-snmp-nms-node.js.git

gclone https://gitlab.edgecenter.io/edgesense/reyaxsol.git
gclone https://gitlab.edgecenter.io/edgesense/uartmgr.git

gclone https://gitlab.edgecenter.io/edgesense/device-odbc.git

gclone https://gitlab.edgecenter.io/edgesense/TowerLight-Sensor.git

gclone https://gitlab.edgecenter.io/edgesense/industrial-protocol-sdk.git
gclone https://gitlab.edgecenter.io/edgesense/device-industry-node.js.git

gclone https://gitlab.edgecenter.io/edgesense/device-opcua-client-node.js.git

gclone https://gitlab.edgecenter.io/edgesense/poc_battery-app-wpf.git
gclone https://gitlab.edgecenter.io/edgesense/device-poc_link-mgt-node.js.git

gclone https://gitlab.edgecenter.io/edgesense/e2i-edge-installer.git
gclone https://gitlab.edgecenter.io/edgesense/e2i-edge-webconsole.git
gclone https://gitlab.edgecenter.io/edgesense/e2i-server-installer.git
