#!/bin/bash
# Written by sammtcbn 2020.7.1
ME=$(basename $0)
VER=0.1

USAGE_STR="$(cat <<EOF
${ME} ${VER}
Usage: ${ME} [OPTIONS] ...

OPTIONS
  es
  esopen
  ag
  ess
  dss
  github
  all
  
Example
  ${ME} esopen

EOF
)"

function usage()
{
    echo "$USAGE_STR"
    exit 0
}

function myclone()
{
    url=$1
    if hash gclone 2> /dev/null; then
        gclone $url
    else
        git clone $url
    fi
}

function f_ag()
{
myclone https://gitlab.edgecenter.io/wise-agent-core/RMM-EI-Agent.git
myclone https://gitlab.edgecenter.io/wise-agent-core/RMM-EI-Agent_Installer.git
myclone https://gitlab.edgecenter.io/wise-agent-core/RMM-EI-Agent_New_UI.git

myclone https://gitlab.edgecenter.io/ei-paas-utility_repo/advtools.git
}

function f_dss()
{
myclone https://gitlab.edgecenter.io/edgesense-ai-server/DeviceON.git
myclone https://gitlab.edgecenter.io/edgesense-ai-server/dss-manifest.git
myclone https://gitlab.edgecenter.io/edgesense-ai-server/deployoffline.git
myclone https://gitlab.edgecenter.io/edgesense-ai-server/deployoffline-build.git
}

function f_es()
{
myclone https://gitlab.edgecenter.io/edgesense/epack.git
myclone https://gitlab.edgecenter.io/edgesense/advins-template.git
myclone https://gitlab.edgecenter.io/edgesense/support-i-alarm-node.js.git
myclone https://gitlab.edgecenter.io/edgesense/advsc.git
myclone https://gitlab.edgecenter.io/edgesense/APIGateway.git
myclone https://gitlab.edgecenter.io/edgesense/mqttbroker.git
myclone https://gitlab.edgecenter.io/edgesense/Service-SDK.git
myclone https://gitlab.edgecenter.io/edgesense/device-net-monitor.git
myclone https://gitlab.edgecenter.io/edgesense/device-process-monitor.git

myclone https://gitlab.edgecenter.io/edgesense/device-snmp-nms-node.js.git

myclone https://gitlab.edgecenter.io/edgesense/reyaxsol.git
myclone https://gitlab.edgecenter.io/edgesense/uartmgr.git

myclone https://gitlab.edgecenter.io/edgesense/device-odbc.git

myclone https://gitlab.edgecenter.io/edgesense/TowerLight-Sensor.git

myclone https://gitlab.edgecenter.io/edgesense/industrial-protocol-sdk.git
myclone https://gitlab.edgecenter.io/edgesense/device-industry-node.js.git

myclone https://gitlab.edgecenter.io/edgesense/device-opcua-client-node.js.git

myclone https://gitlab.edgecenter.io/edgesense/poc_battery-app-wpf.git
myclone https://gitlab.edgecenter.io/edgesense/device-poc_link-mgt-node.js.git

myclone https://gitlab.edgecenter.io/edgesense/e2i-edge-installer.git
myclone https://gitlab.edgecenter.io/edgesense/e2i-edge-webconsole.git
myclone https://gitlab.edgecenter.io/edgesense/e2i-server-installer.git

myclone https://gitlab.edgecenter.io/edgesense/DBMService.git
myclone https://gitlab.edgecenter.io/edgesense/InfluxDB.git

myclone https://gitlab.edgecenter.io/edgesense/grafana.git
}

function f_esopen()
{
myclone https://gitlab.edgecenter.io/edgesense-open/advlog-node.js.git
myclone https://gitlab.edgecenter.io/edgesense-open/agentlite-node.js.git
myclone https://gitlab.edgecenter.io/edgesense-open/device-template-node.js.git
myclone https://gitlab.edgecenter.io/edgesense-open/advsc-binary.git
}

function f_ess()
{
myclone https://gitlab.edgecenter.io/eiss_cloud_solution_team/node-red.git
}

function f_github()
{
myclone https://github.com/ADVANTECH-Corp/WiseSnail.git
myclone https://github.com/ADVANTECH-Corp/agentlite.git
myclone https://github.com/ADVANTECH-Corp/APIGateway.git
}

function f_all()
{
f_ag
f_dss
f_es
f_esopen
f_ess
f_github
}

if [ -z "${1}" ]; then
    usage
fi

for opt in $@
do
    case $opt in
      ag)     f_ag;;
      dss)    f_dss;;
      es)     f_es;;
      esopen) f_esopen;;
      ess)    f_ess;;
      github) f_github;;
      all)    f_all;;
    esac
done
