#!/bin/bash

source config
source utils

TOPIC="/cagent/admin/${HANDLER}/agentcallbackreq"

TS=$(date +%s)000

PAYLOAD="$(cat <<-EOF
{
  "susiCommData": {
    "requestID": 1001,
    "catalogID": 4,
    "commCmd": 2051,
    "handlerName": "general"
  }
}
EOF
)"

mqtt_pub ${TOPIC} "${PAYLOAD}"
