#!/bin/bash

ME=$(basename $0)

source config

TOPIC="/cagent/admin/${HANDLER}/agentcallbackreq"

INTERVAL=10

USAGE_STR="$(cat <<EOF
Usage: ${ME} [OPTION]...

OPTIONS
  -s <INTERVAL>
      assign auto report interval (second) , default is ${INTERVAL}

  -h  display this help and exit

EOF
)"

function usage()
{
    echo "$USAGE_STR"
    exit 0
}

while getopts "s:h" opt; do
    case $opt in
    h)
       usage
       ;;
    s)
       INTERVAL=$OPTARG
       ;;
    esac
done

PAYLOAD="$(cat <<-EOF
{
  "susiCommData": {
      "commCmd": 2053,
      "requestItems": {
          "All": {}
      },
      "autoUploadIntervalSec": ${INTERVAL},
      "handlerName": "general"
  }
}
EOF
)"

mosquitto_pub -h ${MQTTIP} -t ${TOPIC} -d -m "${PAYLOAD}"
if [ $? != 0 ]; then
    echo "error"
fi
