#!/bin/bash

ME=$(basename $0)

source config
source utils

TOPIC="/cagent/admin/${HANDLER}/agentcallbackreq"

TS=$(Gen_TS)

INTERVAL=10

USAGE_STR="$(cat <<EOF
Usage: ${ME} [OPTION]...

OPTIONS
  -s <INTERVAL>
      assign auto report interval (second) , default is ${INTERVAL}

  -h  display this help and exit

EOF
)"

function usage()
{
    echo "$USAGE_STR"
    exit 0
}

while getopts "s:h" opt; do
    case $opt in
    h)
       usage
       ;;
    s)
       INTERVAL=$OPTARG
       ;;
    esac
done

PAYLOAD="$(cat <<-EOF
{
  "susiCommData": {
      "catalogID": 4,
      "commCmd": 2053,
      "requestItems": {
          "All": {}
      },
      "autoUploadIntervalSec": ${INTERVAL},
      "handlerName": "general",
      "sendTS": {
          "$date": ${TS}
      }
  }
}
EOF
)"

mqtt_pub ${TOPIC} "${PAYLOAD}"
