#!/bin/bash

source config
source utils

TOPIC="/cagent/admin/${HANDLER}/agentcallbackreq"

PAYLOAD="$(cat <<-EOF
{
  "susiCommData": {
      "requestID": 1001,
      "commCmd": 2056,
      "requestItems": {
          "All": {}
      },
      "handlerName": "general"
  }
}
EOF
)"

mqtt_pub ${TOPIC} "${PAYLOAD}"
