#!/bin/bash
HANDLER="DemoPlugin"
VERSION="1.0.1"
MANUFACTURE=Advantech
DESCRIPTION="This is a demo plug-in"

MQTTIP=localhost

REPORT_INTERVAL=3

SENSOR_FILE=sensorlist1.csv
SENSOR_UPDATE_SCRIPT=sensorlist1_update_script

#SENSOR_FILE=sensorlist2.csv
#SENSOR_UPDATE_SCRIPT=sensorlist2_update_script

#DEBUG_MQTT_MSG=Y
