#!/bin/bash

source config

TOPIC="/cagent/admin/${HANDLER}/deviceinfo"

TS=$(date +%s)000

function random_fun()
{
    echo $(( ( RANDOM % 99 )  + 1 ))
}

temperature=$(random_fun)
humidity=$(random_fun)

PAYLOAD="$(cat <<-EOF
{
  "susiCommData": {
    "data": {
      "${HANDLER}": {
        "SenData": {
          "bn": "SenData",
          "e": [
            {
              "n": "Count",
              "v": 1
            },
            {
              "n": "Temperature",
              "v": ${temperature}
            },
            {
              "n": "Humidity",
              "v": ${humidity}
            },
            {
              "n": "Voltage",
              "v": 12
            }
          ]
        },
        "opTS": {
          "$date": ${TS}
        }
      }
    },
    "commCmd": 2055,
    "requestID": 2001,
    "agentID": "${HANDLER}",
    "handlerName": "general",
    "sendTS": ${TS}
  }
}
EOF
)"

mosquitto_pub -h ${MQTTIP} -t ${TOPIC} -d -m "${PAYLOAD}"
if [ $? != 0 ]; then
    echo "error"
fi
