#!/bin/bash

source config
source utils

TOPIC="/cagent/admin/${HANDLER}/deviceinfo"

TS=$(date +%s)000

source ${SENSOR_UPDATE_SCRIPT}

function generate_all_sensor_data_payload()
{
    local idx=0

    for i in "${!SensorType[@]}"
    do
        idx=$(($idx + 1))

        if [ "${SensorType[$i]}" == "v" ]; then
            sensor_payload=$(Gen_Num_Data ${i} ${SensorValue[$i]})
        elif [ "${SensorType[$i]}" == "sv" ]; then
            sensor_payload=$(Gen_String_Data ${i} "${SensorValue[$i]}")
        fi

        if [[ $idx -ne ${TotalSensorNum} ]]; then
            # is NOT last line
            fullpayload="{ ${sensor_payload} },"
        else
            # IS last line
            fullpayload="{ ${sensor_payload} }"
        fi

        echo ${fullpayload}
done
}

PAYLOAD_SAMPLE="$(cat <<-EOF
{
  "susiCommData": {
    "data": {
      "${HANDLER}": {
        "SenData": {
          "bn": "SenData",
          "e": [
            {
              "n": "Count",
              "v": 1
            },
            {
              "n": "Temperature",
              "v": ${temperature}
            },
            {
              "n": "Humidity",
              "v": ${humidity}
            },
            {
              "n": "Voltage",
              "v": 12
            }
          ]
        },
        "opTS": {
          "$date": ${TS}
        }
      }
    },
    "commCmd": 2055,
    "requestID": 2001,
    "agentID": "${HANDLER}",
    "handlerName": "general",
    "sendTS": ${TS}
  }
}
EOF
)"

SENSOR_FULL_PAYLOAD=$(generate_all_sensor_data_payload)

PAYLOAD="$(cat <<-EOF
{
  "susiCommData": {
    "data": {
      "${HANDLER}": {
        "SenData": {
          "bn": "SenData",
          "e": [
${SENSOR_FULL_PAYLOAD}
          ]
        },
        "opTS": {
          "$date": ${TS}
        }
      }
    },
    "commCmd": 2055,
    "requestID": 2001,
    "agentID": "${HANDLER}",
    "handlerName": "general",
    "sendTS": ${TS}
  }
}
EOF
)"

#mqtt_pub ${TOPIC} "${PAYLOAD_SAMPLE}"
mqtt_pub ${TOPIC} "${PAYLOAD}"
