#!/bin/bash

source config

TOPIC="/cagent/admin/${HANDLER}/agentinfoack"

TS=$(date +%s)000

PAYLOAD="$(cat <<-EOF
{
  "susiCommData": {
    "devID": "${HANDLER}",
    "hostname": "${HANDLER}",
    "sn": "",
    "mac": "",
    "version": "${VERSION}",
    "type": "Service",
    "product": "${HANDLER}",
    "manufacture": "Advantech",
    "status": 1,
    "commCmd": 1,
    "requestID": 21,
    "agentID": "${HANDLER}",
    "handlerName": "general",
    "sendTS": ${TS}
  }
}
EOF
)"

mosquitto_pub -h ${MQTTIP} -t ${TOPIC} -d -m "${PAYLOAD}"
