#!/bin/bash

source config
source utils

TOPIC="/cagent/admin/${HANDLER}/agentactionreq"

TS=$(date +%s)000

function generate_all_sensor_capability_payload()
{
    local idx=0

    for i in "${!SensorType[@]}"
    do
        idx=$(($idx + 1))

        if [ "${SensorType[$i]}" == "v" ]; then
            sensor_payload=$(Gen_Num_Capability ${i} ${SensorAccess[$i]} ${SensorValue[$i]})
        elif [ "${SensorType[$i]}" == "sv" ]; then
            sensor_payload=$(Gen_String_Capability ${i} ${SensorAccess[$i]} ${SensorValue[$i]})
        fi

        if [[ $idx -ne ${TotalSensorNum} ]]; then
            # is NOT last line
            fullpayload="{ ${sensor_payload} },"
        else
            # IS last line
            fullpayload="{ ${sensor_payload} }"
        fi

        echo ${fullpayload}
done
}

PAYLOAD_SAMPLE="$(cat <<-EOF
{
  "susiCommData": {
    "infoSpec": {
      "${HANDLER}": {
        "info": {
          "bn": "info",
          "e": [
            {
              "n": "type",
              "sv": "Demo",
              "asm": "r"
            },
            {
              "n": "name",
              "sv": "${HANDLER}",
              "asm": "r"
            },
            {
              "n": "description",
              "sv": "${DESCRIPTION}",
              "asm": "r"
            },
            {
              "n": "version",
              "sv": "${VERSION}",
              "asm": "r"
            },
            {
              "n": "selfWeb",
              "bv": false,
              "asm": "r"
            }
          ]
        },
        "SenData": {
          "bn": "SenData",
          "e": [
            {
              "n": "Temperature",
              "u": "Cel",
              "v": 26,
              "min": -40,
              "max": 120,
              "asm": "r"
            },
            {
              "n": "Humidity",
              "u": "%",
              "v": 65,
              "min": 0,
              "max": 100,
              "asm": "r"
            },
            {
              "n": "Voltage",
              "u": "V",
              "v": 12,
              "min": 10,
              "max": 15,
              "asm": "r"
            },
            {
              "n": "Count",
              "u": "",
              "v": 0,
              "asm": "rw"
            }
          ]
        }
      }
    },
    "commCmd": 2052,
    "requestID": 2001,
    "agentID": "${HANDLER}",
    "handlerName": "general",
    "sendTS": ${TS}
  }
}
EOF
)"

SENSOR_FULL_PAYLOAD=$(generate_all_sensor_capability_payload)

PAYLOAD="$(cat <<-EOF
{
  "susiCommData": {
    "infoSpec": {
      "${HANDLER}": {
        "info": {
          "bn": "info",
          "e": [
            {
              "n": "type",
              "sv": "Demo",
              "asm": "r"
            },
            {
              "n": "name",
              "sv": "${HANDLER}",
              "asm": "r"
            },
            {
              "n": "description",
              "sv": "${DESCRIPTION}",
              "asm": "r"
            },
            {
              "n": "version",
              "sv": "${VERSION}",
              "asm": "r"
            },
            {
              "n": "selfWeb",
              "bv": false,
              "asm": "r"
            }
          ]
        },
        "SenData": {
          "bn": "SenData",
          "e": [
${SENSOR_FULL_PAYLOAD}
          ]
        }
      }
    },
    "commCmd": 2052,
    "requestID": 2001,
    "agentID": "${HANDLER}",
    "handlerName": "general",
    "sendTS": ${TS}
  }
}
EOF
)"

#mqtt_pub ${TOPIC} "${PAYLOAD_SAMPLE}"
mqtt_pub ${TOPIC} "${PAYLOAD}"
