#!/bin/bash

source config
source utils

TOPIC="/cagent/admin/${HANDLER}/agentinfoack"

TS=$(date +%s)000

PAYLOAD="$(cat <<-EOF
{
  "susiCommData": {
    "devID": "${HANDLER}",
    "hostname": "${HANDLER}",
    "sn": "",
    "mac": "",
    "version": "${VERSION}",
    "type": "Service",
    "product": "${HANDLER}",
    "manufacture": "${MANUFACTURE}",
    "status": 1,
    "commCmd": 1,
    "requestID": 21,
    "agentID": "${HANDLER}",
    "handlerName": "general",
    "sendTS": ${TS}
  }
}
EOF
)"

mqtt_pub ${TOPIC} "${PAYLOAD}"
