#!/bin/bash
# https://github.com/sammtcbn/advutil
# Written by sammtcbn 2018.10.12
ME=$(basename $0)

function usage() {
    echo "Usage:"
    echo "  ${ME}"
    echo "    - ip use default 127.0.0.1"
    echo "  ${ME} [ip]"
    exit 1
}

IP=127.0.0.1
PORT=3000

if [ ! -z "${1}" ]; then
    IP=${1}
fi

CMD="curl -s http://${IP}:${PORT}/restapi/WSNManage/SenHub/AllSenHubList | python -m json.tool"
echo ${CMD}
eval ${CMD}
