#!/bin/bash
# https://github.com/sammtcbn/advutil
# Last modified by sammtcbn 2019.2.15
ME=$(basename $0)

function usage() {
    echo "Usage:"
    echo "  ${ME} [option]"
    echo "    0/stop - stop uartmgr service"
    echo "    1/rs   - restart uartmgr service"
    echo "    2/st   - uartmgr service status"
    echo "    3/log  - show uartmgr log"
    exit 1
}

function show_ps() {
    echo
    echo "ps -aux | grep uartmgr"
    ps -aux | grep [u]artmgr
    echo
}

if [ -z "${1}" ]; then
    usage
fi

opt=${1}

case $opt in
    0) ;&
    stop)
        sudo systemctl stop uartmgr.service
        show_ps
        ;;
    1) ;&
    rs)
        sudo systemctl restart uartmgr.service
        show_ps
        ;;
    2) ;&
    st)
        show_ps
        sudo systemctl status uartmgr.service
        ;;
    3) ;&
    log)
        cat /var/log/syslog | grep -a uartmgr
        ;;
esac
