#!/bin/bash

Sensor_String_Value_update Host_Name "$(hostname)"
Sensor_String_Value_update System_Current_Time "$(date '+%Y-%m-%d %H:%M:%S')"
Sensor_String_Value_update System_Up_Time "$(uptime -s)"
Sensor_String_Value_update HDD_Available_Size "$(df -h --output=avail / | tail -n1 | xargs)"
