#!/bin/bash

function is_service_running ()
{
    systemctl is-active --quiet $1
    ret_code=$?
    if [ $ret_code = 0 ]; then
        echo "true"
    else
        echo "false"
    fi
}

Sensor_String_Value_update Host_Name "$(hostname)"
Sensor_String_Value_update System_Current_Time "$(date '+%Y-%m-%d %H:%M:%S')"
Sensor_String_Value_update System_Up_Time "$(uptime -s)"
Sensor_String_Value_update HDD_Available_Size "$(df -h --output=avail / | tail -n1 | xargs)"

Sensor_Bool_Value_update sshd_running $(is_service_running sshd)
Sensor_Bool_Value_update syslog_running $(is_service_running syslog)
Sensor_Bool_Value_update abcd_running $(is_service_running abcd)
