net start mosquitto
net start SAWatchdog
net start WISEAgentService
net start nginx
net start APIGateway
net start device-net-monitor
net start device-process-monitor
net start support-i-alarm
net start NodeRed
net start device-opcua-client
net start device-modbus-service
net start device-modbus-protocol
net start device-wascada
net start device-odbc
